#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$app_cli_side = match ((new ArgvInput())->getParameterOption('--side') ?? null){
    null=>'common',
    'be'=>'backend',
    'fe'=>'frontend'
};

$app->instance('app.cli.side', $app_cli_side);

$new_args = array_filter($_SERVER['argv'],function ($val){
    if(str_starts_with($val, '--side=')){
        --$_SERVER['argc'];
        return false;
    }
    return true;
});

$_SERVER['argv']=$new_args;

$status = $app->handleCommand(new ArgvInput());

exit($status);
